GET http://localhost:5052/acquirenti 

########
POST http://localhost:5050/acquirenti HTTP/1.1
Content-Type: application/json

{
    "codiceAcquirenti": "001",
    "denominazione": "srl",
    "indirizzo": "via della republica",
    "cap": 51031,
    "partitaIva": 1325487234575,
    "codiceFiscale": "MBNSY3546Y343D",
    "citta": "firenze"
}

########
GET http://localhost:5052/merce